language: node_js
node_js:
  - '10'
cache: yarn
script:
  - yarn test
  - yarn run build:sb
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: storybook-build
  on:
    branch: master
